name 'httpd_ak'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures httpd_ak'
long_description 'Installs/Configures httpd_ak'
version '0.1.0'
