----kill sessions
begin
 for sessions in ( select sid, serial# 
                    from   v$session 
                    where  username = 'AKBELVIS4TSM411LB')
  loop
    execute immediate 'alter system kill session '''||sessions.sid||','||sessions.serial#||'''';
  end loop;
end;
/
---- drop user 
DROP USER AKBELVIS4TSM411LB CASCADE;
---- create user
CREATE USER AKBELVIS4TSM411LB
  IDENTIFIED BY "12years"
  DEFAULT TABLESPACE AKBELVIS4TSM411LB
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for new dbuser 
  GRANT CONNECT TO AKBELVIS4TSM411LB;
  ALTER USER AKBELVIS4TSM411LB DEFAULT ROLE ALL;
  -- 13 System Privileges new dbuser
  GRANT CREATE DATABASE LINK TO AKBELVIS4TSM411LB;
  GRANT CREATE JOB TO AKBELVIS4TSM411LB;
  GRANT CREATE MATERIALIZED VIEW TO AKBELVIS4TSM411LB;
  GRANT CREATE PROCEDURE TO AKBELVIS4TSM411LB;
  GRANT CREATE PUBLIC DATABASE LINK TO AKBELVIS4TSM411LB;
  GRANT CREATE PUBLIC SYNONYM TO AKBELVIS4TSM411LB;
  GRANT CREATE SEQUENCE TO AKBELVIS4TSM411LB;
  GRANT CREATE SESSION TO AKBELVIS4TSM411LB;
  GRANT CREATE SYNONYM TO AKBELVIS4TSM411LB;
  GRANT CREATE TABLE TO AKBELVIS4TSM411LB;
  GRANT CREATE TRIGGER TO AKBELVIS4TSM411LB;
  GRANT CREATE VIEW TO AKBELVIS4TSM411LB;
  GRANT SELECT ANY DICTIONARY TO AKBELVIS4TSM411LB;
  -- 2 Tablespace Quotas for #{node['enetgas']['dbuser']} 
  ALTER USER AKBELVIS4TSM411LB QUOTA UNLIMITED ON AKBELVIS4TSM411LB;
  ALTER USER AKBELVIS4TSM411LB QUOTA UNLIMITED ON USERS;
  -- 1 Object Privilege for #{node['enetgas']['dbuser']} 
    GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO AKBELVIS4TSM411LB;
commit;
exit