----kill sessions
begin
 for sessions in ( select sid, serial# 
                    from   v$session 
                    where  username = 'ENET_POWER_AUTOMATISIERUNG ')
  loop
    execute immediate 'alter system kill session '''||sessions.sid||','||sessions.serial#||'''';
  end loop;
end;
/
---- drop user 
DROP USER ENET_POWER_AUTOMATISIERUNG  CASCADE;
---- create user
CREATE USER ENET_POWER_AUTOMATISIERUNG 
  IDENTIFIED BY "12years"
  DEFAULT TABLESPACE ENET_POWER_AUTOMATISIERUNG   
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK;
  -- 1 Role for new dbuser 
  GRANT CONNECT TO ENET_POWER_AUTOMATISIERUNG ;
  ALTER USER AKBELVIS4TSM411LB DEFAULT ROLE ALL;
  -- 13 System Privileges new dbuser
  GRANT CREATE DATABASE LINK TO ENET_POWER_AUTOMATISIERUNG ;
  GRANT CREATE JOB TO ENET_POWER_AUTOMATISIERUNG ;
  GRANT CREATE MATERIALIZED VIEW TO ENET_POWER_AUTOMATISIERUNG ;
  GRANT CREATE PROCEDURE TO ENET_POWER_AUTOMATISIERUNG ;
  GRANT CREATE PUBLIC DATABASE LINK TO ENET_POWER_AUTOMATISIERUNG ;
  GRANT CREATE PUBLIC SYNONYM TO ENET_POWER_AUTOMATISIERUNG ;
  GRANT CREATE SEQUENCE TO ENET_POWER_AUTOMATISIERUNG ;
  GRANT CREATE SESSION TO ENET_POWER_AUTOMATISIERUNG ;
  GRANT CREATE SYNONYM TO ENET_POWER_AUTOMATISIERUNG ;
  GRANT CREATE TABLE TO ENET_POWER_AUTOMATISIERUNG ;
  GRANT CREATE TRIGGER TO ENET_POWER_AUTOMATISIERUNG ;
  GRANT CREATE VIEW TO ENET_POWER_AUTOMATISIERUNG ;
  GRANT SELECT ANY DICTIONARY TO ENET_POWER_AUTOMATISIERUNG ;
  -- 2 Tablespace Quotas for created user
  ALTER USER AKBELVIS4TSM411LB QUOTA UNLIMITED ON ENET_POWER_AUTOMATISIERUNG ;
  ALTER USER AKBELVIS4TSM411LB QUOTA UNLIMITED ON USERS;
  -- 1 Object Privilege for created user
    GRANT READ, WRITE ON DIRECTORY DATA_PUMP_DIR TO ENET_POWER_AUTOMATISIERUNG ;
commit;
exit